import {
  AlertTriangle,
  CircleAlert,
  Coins,
  DollarSign,
  Hash,
  Layers,
  Timer,
  Users,
  type LucideIcon,
} from 'lucide-react'
import type { ReactNode } from 'react'
import { useTranslation } from 'react-i18next'

import { IconBadge, type IconBadgeTone } from '@/components/ui/icon-badge'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'

import { getActiveUserRateClassName } from '../lib/active-user-rate'
import type { CostBucket, DepartmentStat } from '../types'
import { ActivityFormulaTooltip } from './activity-formula-tooltip'

export function DepartmentStatsCards(props: { stat: DepartmentStat }) {
  const { t } = useTranslation()
  const stat = props.stat

  const formatTokens = (tokens: number | undefined): string => {
    if (!tokens) return '0'
    return `${(tokens / 1_0000_0000).toFixed(2)} 亿`
  }

  const buildTokenBreakdownTooltip = (): ReactNode => {
    const breakdownRows: { label: string; desc: string; value: number }[] = [
      {
        label: t('Uncached Input'),
        desc: t('Uncached input tokens actually sent to the model'),
        value: stat.uncached_input_tokens ?? 0,
      },
      {
        label: t('Uncached Output'),
        desc: t('Output tokens generated by the model'),
        value: stat.uncached_output_tokens ?? 0,
      },
      {
        label: t('Cache Read'),
        desc: t('Input tokens served from the prompt cache'),
        value: stat.cache_read_tokens ?? 0,
      },
      {
        label: t('Cache Write'),
        desc: t('Input tokens written to the prompt cache'),
        value: stat.cache_write_tokens ?? 0,
      },
    ]
    return (
      <div className='text-background max-w-[16rem] space-y-1.5'>
        <div className='flex items-baseline justify-between gap-4'>
          <span className='text-xs'>{t('Total Tokens')}</span>
          <span className='font-mono text-xs font-semibold'>
            {formatTokens(stat.total_tokens)}
          </span>
        </div>
        <div className='border-border/40 space-y-1.5 border-t pt-1.5'>
          {breakdownRows.map((row) => (
            <div key={row.label}>
              <div className='flex items-baseline justify-between gap-4'>
                <span className='text-xs font-medium'>{row.label}</span>
                <span className='font-mono text-xs'>
                  {formatTokens(row.value)}
                </span>
              </div>
              <div className='font-sans text-[11px] leading-snug'>
                {row.desc}
              </div>
            </div>
          ))}
        </div>
      </div>
    )
  }

  const formatCNY = (amount: number | undefined): string => {
    if (!amount) return '¥0'
    return `¥${amount.toFixed(2)}`
  }

  const formatRequests = (count: number | undefined): string => {
    if (!count) return '0'
    if (count >= 1_0000) {
      return `${(count / 1_0000).toFixed(2)} 万`
    }
    return count.toLocaleString()
  }

  const formatCostBucketLabel = (bucket: CostBucket): string => {
    if (bucket.max_amount_cny === 0) {
      if (bucket.min_amount_cny === 0) {
        return t('Spent ¥0')
      }
      return t('Spent over ¥{{min}}', { min: bucket.min_amount_cny })
    }
    return t('Spent ¥{{min}}~¥{{max}}', {
      min: bucket.min_amount_cny,
      max: bucket.max_amount_cny,
    })
  }

  const buildCostDistributionTooltip = (): ReactNode => {
    const costBuckets = stat.cost_buckets ?? []
    if (costBuckets.length === 0) {
      return null
    }
    return (
      <div className='text-background max-w-[16rem] space-y-1.5'>
        <div className='flex items-baseline justify-between gap-4'>
          <span className='text-xs font-medium'>{t('Cost Distribution')}</span>
        </div>
        <div className='border-border/40 space-y-1.5 border-t pt-1.5'>
          {costBuckets.map((bucket) => (
            <div
              key={`${bucket.min_amount_cny}-${bucket.max_amount_cny}`}
              className='flex items-baseline justify-between gap-4'
            >
              <span className='text-xs'>{formatCostBucketLabel(bucket)}</span>
              <span className='font-mono text-xs font-semibold'>
                {t('{{count}} people', { count: bucket.users })}
              </span>
            </div>
          ))}
        </div>
      </div>
    )
  }

  const activeUserRate = stat.active_user_rate ?? 0
  const tokensPerActiveUser =
    (stat.avg_tokens_per_active_user_mt ?? 0) * 1_000_000
  const activeUserRateClassName = getActiveUserRateClassName(activeUserRate)
  const highCostUserRate = stat.high_cost_user_rate ?? 0
  const highCostUserRateClassName = getActiveUserRateClassName(highCostUserRate)

  const errorRate = stat.error_rate ?? 0
  const cacheReadTokens = stat.cache_read_tokens ?? 0
  const totalInputTokens =
    (stat.uncached_input_tokens ?? 0) +
    cacheReadTokens +
    (stat.cache_write_tokens ?? 0)
  // 与 API 周报口径一致：缓存写入属于未命中，同样计入分母。
  const cacheHitRate =
    totalInputTokens > 0 ? (cacheReadTokens / totalInputTokens) * 100 : 0

  const items: {
    title: string
    titleSuffix?: ReactNode
    value: ReactNode
    desc?: string
    icon: LucideIcon
    iconTone: IconBadgeTone
    valueClassName?: string
    tooltip?: ReactNode
    showTooltipIcon?: boolean
  }[] = [
    {
      title: t('Total Tokens'),
      value: formatTokens(stat.total_tokens),
      desc: t('Statistical tokens'),
      icon: Layers,
      iconTone: 'chart-4',
      tooltip: buildTokenBreakdownTooltip(),
      showTooltipIcon: true,
    },
    {
      title: t('Total Cost'),
      value: formatCNY(stat.total_amount_cny),
      desc: t('Statistical quota'),
      icon: Coins,
      iconTone: 'success',
    },
    {
      title: t('Unit Price'),
      value: `${
        !stat.unit_price_per_100m_tokens
          ? '¥0'
          : `¥${stat.unit_price_per_100m_tokens.toFixed(2)}`
      }/${t('100M Tokens')}`,
      desc: t('Unit price per 100M tokens'),
      icon: DollarSign,
      iconTone: 'warning',
    },
    {
      title: t('Total Requests'),
      value: formatRequests(stat.total_requests),
      desc: t('Statistical count'),
      icon: Hash,
      iconTone: 'info',
    },
    {
      title: t('Avg Response Time'),
      value: `${(stat.avg_use_time ?? 0).toFixed(1)}s`,
      desc: t('Average response time'),
      icon: Timer,
      iconTone: 'chart-2',
    },
    {
      title: t('Unregistered / Registered'),
      value: (
        <>
          <span className='text-warning'>
            {(stat.unregistered_users ?? 0).toLocaleString()}
          </span>
          <span className='text-muted-foreground'> / </span>
          <span className='text-success'>
            {(stat.registered_users ?? 0).toLocaleString()}
          </span>
        </>
      ),
      desc: t('Unregistered and registered people count'),
      icon: Users,
      iconTone: 'chart-3',
    },
    {
      title: t('Users / Share'),
      titleSuffix: (
        <ActivityFormulaTooltip formula={stat.active_user_formula} />
      ),
      value: `${(stat.active_users ?? 0).toLocaleString()} / ${activeUserRate.toFixed(1)}%`,
      desc: t('Users and their share during the selected period'),
      icon: Users,
      iconTone: 'primary',
      valueClassName: activeUserRateClassName,
    },
    {
      title: t('Cost >10 Users / Share'),
      titleSuffix: (
        <Tooltip>
          <TooltipTrigger
            render={
              <button
                type='button'
                className='text-muted-foreground/70 hover:text-foreground shrink-0 transition-colors'
                aria-label={t('View cost distribution')}
              />
            }
          >
            <CircleAlert className='size-3 sm:size-3.5' />
          </TooltipTrigger>
          <TooltipContent>
            <div className='font-sans text-xs'>
              {buildCostDistributionTooltip()}
            </div>
          </TooltipContent>
        </Tooltip>
      ),
      value: `${(stat.high_cost_users ?? 0).toLocaleString()} / ${highCostUserRate.toFixed(1)}%`,
      desc: t('Users spending more than ¥10'),
      icon: DollarSign,
      iconTone: 'destructive',
      valueClassName: highCostUserRateClassName,
    },
    {
      title: t('Tokens per Active User'),
      value: formatTokens(tokensPerActiveUser),
      desc: t('Based on active users only'),
      icon: Layers,
      iconTone: 'chart-4',
      tooltip: formatTokens(tokensPerActiveUser),
    },
    {
      title: t('Error Rate / Cache Hit Rate'),
      value: (
        <>
          <span className='text-destructive'>{errorRate.toFixed(1)}%</span>
          <span className='text-muted-foreground'> / </span>
          <span className='text-success'>{cacheHitRate.toFixed(1)}%</span>
        </>
      ),
      desc: t('Request error rate and cache hit rate'),
      icon: AlertTriangle,
      iconTone: 'destructive',
    },
  ]

  return (
    <div className='overflow-hidden rounded-lg border'>
      <div className='divide-border/60 grid min-w-0 grid-cols-2 divide-x sm:grid-cols-3 lg:grid-cols-5'>
        {items.map((item) => {
          const Icon = item.icon
          let renderedValue: ReactNode

          if (item.tooltip && item.showTooltipIcon) {
            renderedValue = (
              <Tooltip>
                <div className='mt-1.5 flex min-w-0 items-center gap-1.5 sm:mt-2'>
                  <div
                    className={cn(
                      'min-w-0 truncate font-mono text-lg font-bold tracking-tight tabular-nums sm:text-2xl',
                      item.valueClassName || 'text-foreground'
                    )}
                  >
                    {item.value}
                  </div>
                  <TooltipTrigger
                    render={
                      <button
                        type='button'
                        className='text-muted-foreground/70 hover:text-foreground shrink-0 -translate-y-3 transition-colors'
                        aria-label={t('View details')}
                      />
                    }
                  >
                    <CircleAlert className='size-3 sm:size-3.5' />
                  </TooltipTrigger>
                </div>
                <TooltipContent>
                  <div className='font-mono text-xs'>{item.tooltip}</div>
                </TooltipContent>
              </Tooltip>
            )
          } else if (item.tooltip) {
            renderedValue = (
              <Tooltip>
                <TooltipTrigger
                  render={
                    <div
                      className={cn(
                        'mt-1.5 max-w-full truncate font-mono text-lg font-bold tracking-tight tabular-nums sm:mt-2 sm:text-2xl',
                        item.valueClassName || 'text-foreground'
                      )}
                    />
                  }
                >
                  {item.value}
                </TooltipTrigger>
                <TooltipContent>
                  <div className='font-mono text-xs'>{item.tooltip}</div>
                </TooltipContent>
              </Tooltip>
            )
          } else {
            renderedValue = (
              <div
                className={cn(
                  'mt-1.5 max-w-full truncate font-mono text-lg font-bold tracking-tight tabular-nums sm:mt-2 sm:text-2xl',
                  item.valueClassName || 'text-foreground'
                )}
              >
                {item.value}
              </div>
            )
          }

          return (
            <div
              key={item.title}
              className='min-w-0 px-3 py-2.5 sm:px-5 sm:py-4'
            >
              <div className='flex min-w-0 items-center gap-1.5 sm:gap-2'>
                <IconBadge
                  tone={item.iconTone}
                  size='stat'
                  className='size-4 rounded-sm sm:size-7 sm:rounded-md [&>svg]:size-2.5 sm:[&>svg]:size-3.5'
                >
                  <Icon />
                </IconBadge>
                <div className='text-muted-foreground min-w-0 truncate text-[11px] leading-4 font-medium tracking-wide sm:text-xs sm:tracking-wider'>
                  {item.title}
                </div>
                {item.titleSuffix}
              </div>
              {renderedValue}
              {item.desc && (
                <div className='text-muted-foreground/60 mt-1 hidden text-[13px] md:block'>
                  {item.desc}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
